'use strict';

// Sześć klas: cztery weteranki z części I (rozwinięte) + dwie nowe.
// attack: podstawowy atak LPM. skills: 5 umiejętności (5 = ulta).
const ClassDB = {
  warrior: {
    id: 'warrior', name: 'Wojownik', icon: '⚔️',
    desc: 'Stal, szał i tarcza. Weteran pierwszej wyprawy.',
    stats: { hp: 130, mp: 40, atk: 13, def: 8, speed: 4.4, crit: .06, spellPower: 0 },
    attack: { type: 'melee', range: 2.0, arc: 2.1, cd: .55, mult: 1, element: 'phys', color: '#ffd8a0' },
    skills: [
      { id: 'w1', name: 'Szał Krwi', icon: '😡', mp: 12, cd: 11, type: 'buff',
        desc: '+60% obrażeń i +15% szybkości na 6s.',
        buff: { icon: '😡', name: 'Szał Krwi', dur: 6, atkPct: .6, spdPct: .15 } },
      { id: 'w2', name: 'Uderzenie Tarczą', icon: '🛡️', mp: 14, cd: 8, type: 'cone',
        desc: 'Cios tarczą w stożku: obrażenia i ogłuszenie.',
        dmg: 22, range: 2.6, arc: 1.9, element: 'phys', status: { type: 'stun', dur: 1.3, chance: 1 } },
      { id: 'w3', name: 'Wirujące Ostrza', icon: '🌪️', mp: 20, cd: 13, type: 'buff',
        desc: 'Przez 4s tniesz wszystko wokół siebie.',
        buff: { icon: '🌪️', name: 'Wirujące Ostrza', dur: 4, aura: { dps: 26, radius: 2.2, element: 'phys' } } },
      { id: 'w4', name: 'Skok Gromu', icon: '⚡', mp: 18, cd: 10, type: 'leap',
        desc: 'Skok do kursora, uderzenie obszarowe i porażenie.',
        dmg: 32, radius: 2.3, range: 6.5, element: 'arcane', status: { type: 'stun', dur: .7, chance: .6 } },
      { id: 'w5', name: 'Gniew Otchłani', icon: '🔥', mp: 30, cd: 45, type: 'buff', ult: true,
        desc: 'ULTA: 8s — +100% obrażeń, 30% kradzieży życia, obrażenia obszarowe.',
        buff: { icon: '🔥', name: 'Gniew Otchłani', dur: 8, atkPct: 1, lifesteal: .3, aura: { dps: 18, radius: 2.4, element: 'fire' } } },
    ],
  },

  mage: {
    id: 'mage', name: 'Mag Żywiołów', icon: '🔮',
    desc: 'Ogień, lód i błyskawica w jednych dłoniach.',
    stats: { hp: 75, mp: 110, atk: 8, def: 3, speed: 4.5, crit: .05, spellPower: .25 },
    attack: { type: 'shot', range: 9, cd: .5, mult: .85, element: 'arcane', color: '#8ab0ff', projSpeed: 11, projSize: .22 },
    skills: [
      { id: 'm1', name: 'Kula Ognia', icon: '🔥', mp: 12, cd: 2.6, type: 'projectile',
        desc: 'Ognisty pocisk — wybucha i podpala.',
        dmg: 26, element: 'fire', speed: 9.5, size: .3, blast: 1.5, status: { type: 'burn', dur: 3, chance: 1 } },
      { id: 'm2', name: 'Nova Mrozu', icon: '❄️', mp: 22, cd: 10, type: 'nova',
        desc: 'Fala mrozu wokół maga — zamraża wrogów.',
        dmg: 24, radius: 3.4, element: 'ice', status: { type: 'freeze', dur: 1.6, chance: 1 } },
      { id: 'm3', name: 'Łańcuch Błyskawic', icon: '⚡', mp: 20, cd: 8, type: 'chain',
        desc: 'Błyskawica przeskakuje na 5 celów.',
        dmg: 30, jumps: 5, range: 8, jumpRange: 4.5, element: 'arcane' },
      { id: 'm4', name: 'Teleportacja', icon: '🌀', mp: 14, cd: 7, type: 'blink',
        desc: 'Natychmiastowy przeskok do kursora.',
        range: 8 },
      { id: 'm5', name: 'Deszcz Meteorów', icon: '☄️', mp: 45, cd: 42, type: 'meteor', ult: true,
        desc: 'ULTA: 7 meteorów spada wokół kursora.',
        count: 7, dmg: 55, radius: 2.0, area: 4.2, range: 9, element: 'fire',
        status: { type: 'burn', dur: 3, chance: 1 } },
    ],
  },

  rogue: {
    id: 'rogue', name: 'Łotrzyk', icon: '🗡️',
    desc: 'Cień, trucizna i krytyki. Szybszy niż wzrok.',
    stats: { hp: 90, mp: 65, atk: 11, def: 4, speed: 5.0, crit: .18, spellPower: 0 },
    attack: { type: 'melee', range: 1.8, arc: 1.6, cd: .38, mult: .8, element: 'phys', color: '#c0e8ff' },
    skills: [
      { id: 'r1', name: 'Rzut Sztyletem', icon: '🔪', mp: 8, cd: 2, type: 'projectile',
        desc: 'Szybki sztylet — powoduje krwawienie.',
        dmg: 18, element: 'phys', speed: 13, size: .18, status: { type: 'bleed', dur: 4, chance: 1 } },
      { id: 'r2', name: 'Krok Cienia', icon: '👤', mp: 12, cd: 9, type: 'stealth',
        desc: 'Niewidzialność 3s. Pierwszy atak z cienia zawsze krytyczny.',
        dur: 3 },
      { id: 'r3', name: 'Wachlarz Ostrzy', icon: '🌀', mp: 18, cd: 8, type: 'volley',
        desc: '7 sztyletów w szerokim wachlarzu.',
        dmg: 15, count: 7, spread: 1.1, element: 'phys', speed: 12, size: .18,
        status: { type: 'bleed', dur: 3, chance: .5 } },
      { id: 'r4', name: 'Zatrute Ostrza', icon: '🧪', mp: 16, cd: 14, type: 'buff',
        desc: 'Przez 8s twoje ataki zatruwają wrogów.',
        buff: { icon: '🧪', name: 'Zatrute Ostrza', dur: 8, onHitStatus: { type: 'poison', dur: 5, chance: 1 } } },
      { id: 'r5', name: 'Egzekucja Cieni', icon: '💀', mp: 30, cd: 40, type: 'execute_chain', ult: true,
        desc: 'ULTA: seria doskoków do 6 wrogów; słabi giną natychmiast.',
        dmg: 45, targets: 6, range: 7, executePct: .3 },
    ],
  },

  necromancer: {
    id: 'necromancer', name: 'Nekromanta', icon: '💀',
    desc: 'Armia umarłych maszeruje na twoje skinienie.',
    stats: { hp: 85, mp: 95, atk: 9, def: 4, speed: 4.4, crit: .05, spellPower: .15 },
    attack: { type: 'shot', range: 8.5, cd: .58, mult: .9, element: 'shadow', color: '#b06aff', projSpeed: 9.5, projSize: .24 },
    skills: [
      { id: 'n1', name: 'Pocisk Pustki', icon: '🌑', mp: 9, cd: 2.4, type: 'projectile',
        desc: 'Mroczny pocisk przeklinający cel.',
        dmg: 24, element: 'shadow', speed: 9, size: .28, status: { type: 'curse', dur: 5, chance: .5 } },
      { id: 'n2', name: 'Wskrzeszenie', icon: '⚰️', mp: 22, cd: 8, type: 'summon',
        desc: 'Przyzywa 2 szkielety (maks. 6 sług).',
        unit: 'skeleton', count: 2, dur: 25 },
      { id: 'n3', name: 'Żniwa Dusz', icon: '🌾', mp: 15, cd: 7, type: 'drain',
        desc: 'Wysysa życie z 3 najbliższych wrogów.',
        dmg: 20, targets: 3, range: 5.5, healPct: .6, element: 'shadow' },
      { id: 'n4', name: 'Klątwa Rozkładu', icon: '🕸️', mp: 20, cd: 9, type: 'curse_area',
        desc: 'Obszar klątwy: wrogowie otrzymują +25% obrażeń i gniją.',
        radius: 2.8, range: 8, dmg: 10, element: 'poison',
        status: { type: 'curse', dur: 6, chance: 1 }, status2: { type: 'poison', dur: 5, chance: 1 } },
      { id: 'n5', name: 'Armia Umarłych', icon: '☠️', mp: 40, cd: 45, type: 'summon', ult: true,
        desc: 'ULTA: 5 wzmocnionych szkieletów i kościany golem na 20s.',
        unit: 'skeleton', count: 5, dur: 20, golem: true, empowered: true },
    ],
  },

  paladin: {
    id: 'paladin', name: 'Paladyn', icon: '⚜️', isNew: true,
    desc: 'Ostatni templariusz Światła. Tarcza żywych.',
    stats: { hp: 115, mp: 70, atk: 12, def: 10, speed: 4.2, crit: .05, spellPower: .1 },
    attack: { type: 'melee', range: 2.1, arc: 2.2, cd: .68, mult: 1.15, element: 'holy', color: '#ffe9a0' },
    skills: [
      { id: 'p1', name: 'Młot Sprawiedliwości', icon: '🔨', mp: 10, cd: 4, type: 'cone',
        desc: 'Potężny cios światła — ogłusza na moment.',
        dmg: 26, range: 2.5, arc: 1.5, element: 'holy', status: { type: 'stun', dur: .8, chance: .8 } },
      { id: 'p2', name: 'Konsekracja', icon: '🕯️', mp: 20, cd: 12, type: 'consecrate',
        desc: 'Święty krąg: pali wrogów, leczy ciebie (5s).',
        dur: 5, dps: 16, hps: 8, radius: 2.6, element: 'holy' },
      { id: 'p3', name: 'Boska Tarcza', icon: '🛡️', mp: 18, cd: 14, type: 'shield',
        desc: 'Bariera pochłaniająca 40% twojego maks. HP (8s).',
        pct: .4, dur: 8 },
      { id: 'p4', name: 'Światło Odkupienia', icon: '✨', mp: 24, cd: 16, type: 'heal',
        desc: 'Leczy 30% HP i zdejmuje negatywne efekty.',
        pct: .3, cleanse: true },
      { id: 'p5', name: 'Awatar Światła', icon: '👼', mp: 35, cd: 50, type: 'buff', ult: true,
        desc: 'ULTA: 10s — skrzydła światła, +50% obrażeń, +10 pancerza, aura święta.',
        buff: { icon: '👼', name: 'Awatar Światła', dur: 10, atkPct: .5, defFlat: 10,
          aura: { dps: 20, radius: 2.6, element: 'holy' } } },
    ],
  },

  hunter: {
    id: 'hunter', name: 'Łowca Pustki', icon: '🏹', isNew: true,
    desc: 'Poluje na to, co wypełzło z Otchłani. Z dystansu.',
    stats: { hp: 80, mp: 70, atk: 10, def: 4, speed: 4.7, crit: .12, spellPower: 0 },
    attack: { type: 'shot', range: 10, cd: .45, mult: .95, element: 'phys', color: '#c8b5ff', projSpeed: 13, projSize: .18 },
    skills: [
      { id: 'h1', name: 'Strzała Pustki', icon: '🎯', mp: 10, cd: 3, type: 'projectile',
        desc: 'Przeszywająca strzała — przebija wszystko na drodze.',
        dmg: 26, element: 'shadow', speed: 15, size: .22, pierce: 99 },
      { id: 'h2', name: 'Salwa', icon: '🏹', mp: 16, cd: 7, type: 'volley',
        desc: '5 strzał w wachlarzu.',
        dmg: 17, count: 5, spread: .7, element: 'phys', speed: 13, size: .18 },
      { id: 'h3', name: 'Wnyki', icon: '🪤', mp: 12, cd: 6, type: 'trap',
        desc: 'Pułapka: unieruchamia i rani (maks. 3).',
        dmg: 30, rootDur: 2, max: 3, radius: .9 },
      { id: 'h4', name: 'Unik Strzelecki', icon: '💨', mp: 14, cd: 8, type: 'dashshot',
        desc: 'Odskok w tył i 3 strzały w kierunku kursora.',
        dmg: 20, count: 3, dashDist: 3.2, element: 'phys', speed: 13 },
      { id: 'h5', name: 'Deszcz Pustki', icon: '🌠', mp: 32, cd: 40, type: 'rain', ult: true,
        desc: 'ULTA: grad strzał pustki nad obszarem przy kursorze (4s).',
        dur: 4, dps: 42, radius: 3.4, range: 9, element: 'shadow' },
    ],
  },
};
